GET http://localhost:3000/api/players 
content-type: application/json

###
GET http://localhost:3000/api/players/byLevel/:id 
content-type: application/json 

###
GET http://localhost:3000/api/players/:id

###

PUT http://localhost:3000/api/players/63fdc702c3204204371a6762
content-type: application/json

{
    "username": "jernberg.alexandra@gmail.com",
    "password": "123456",
    "firstname": "Alexandra",
    "lastname": "Jernberg",
    "gender": "female",
    "side": "backhand",
    "level": "6"
}
###

POST http://localhost:3000/api/players/register 
content-type: application/json

{
    "username": "jernberg.alexandra@gmail.com",
    "password": "123456",
    "firstname": "Alexandra",
    "lastname": "Jernberg",
    "gender": "female",
    "side": "backhand",
    "level": "5"
}

###


POST http://localhost:3000/api/players/login 
content-type: application/json

###

POST http://localhost:3000/api/players/logout 
content-type: application/json

###

POST http://localhost:3000/api/players/:id 
content-type: application/json

###