GET http://localhost:3000/api/players 
content-type: application/json

###
GET http://localhost:3000/api/players/byLevel/5
content-type: application/json 

###
GET http://localhost:3000/api/players/640213ec8e50cc16b034bb3c

###

PUT http://localhost:3000/api/players/64022bff5f4fcdba4fee295d
content-type: application/json

{
     "username": "mio.testsson@mail.com",
    "password": "123456",
    "firstname": "Mio",
    "lastname": "Testsson",
    "gender": "male",
    "side": "backhand",
    "level": "5"
}
###

POST http://localhost:3000/api/players/register 
content-type: application/json

{
    "username": "mio.testsson@mail.com",
    "password": "123456",
    "firstname": "Mio",
    "lastname": "Testsson",
    "gender": "male",
    "side": "backhand",
    "level": "7"
}


###

POST http://localhost:3000/api/players/login
content-type: application/json

{
    "username": "mio.testsson@mail.com",
    "password": "123456"
}


###

POST http://localhost:3000/api/players/logout 
content-type: application/json

###

DELETE  http://localhost:3000/api/players/640205b7206edf49af7ce95f
content-type: application/json

###